trigger:
- master

stages:
- stage: Build
  jobs:
  - job: "PublishIngress"
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ingress'
      inputs:
        PathtoPublish: ingress.yaml
        ArtifactName: ingress
- stage: "Release"
  variables:
    namespace: 'ingress-basic'
  jobs:
  - job: "Release"
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: Kubernetes@1
      displayName: 'kubectl login'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Solvex Dev 8'
        azureResourceGroup: 'web-monitors-dev-rg'
        kubernetesCluster: 'acap-monitor-aks-dev'
        namespace: '$(namespace)'
        command: login
    - task: Kubernetes@1
      displayName: 'create ingress route'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Solvex Dev 8'
        azureResourceGroup: 'web-monitors-dev-rg'
        kubernetesCluster: 'acap-monitor-aks-dev'
        useClusterAdmin: true
        namespace: '$(namespace)'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/ingress.yaml'
